name: news_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

# Dependencies specify other packages that your package needs in order to work.

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  salomon_bottom_bar: ^3.3.2
  font_awesome_flutter: ^10.4.0
  lottie: 
  carousel_slider: ^4.2.1
  http: 
  get: 
  shared_preferences: 
  sqflite: ^2.2.8+4
  path:
  animated_splash_screen: ^1.3.0
  shimmer: ^3.0.0
  loading_animation_widget: ^1.2.0+4
  youtube_player_flutter: ^8.1.2
  share_plus: ^7.0.2
  smooth_page_indicator: ^1.1.0
  webview_flutter: ^4.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/animatednews.json

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
